version: '3.9'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 1001-stories-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev