services:
  playwright-test:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: playwright-diagnostics
    environment:
      - CI=true
      - HEADLESS=true
      - NODE_ENV=test
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - ./tests:/app/tests
      - ./playwright.config.ts:/app/playwright.config.ts
      - ./test-results:/test-results
      - ./playwright-report:/app/playwright-report
      - ./screenshots:/app/screenshots
    command: >
      sh -c "
        echo '🚀 Starting Playwright diagnostic test...' &&
        npx playwright test tests/volunteer-submit-diagnostics.spec.ts --reporter=list --reporter=html &&
        echo '✅ Test complete. Results saved to /test-results/'
      "
    networks:
      - test-network

networks:
  test-network:
    driver: bridge