version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 1001-stories-app
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://1001stories.seedsofempowerment.org
      - DATABASE_URL=postgresql://${DB_USER:-stories_user}:${DB_PASSWORD:-stories_password_123}@postgres:5432/stories_db
    volumes:
      - ./uploads:/app/uploads
      - ./public/books:/app/public/books
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: 1001-stories-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: 1001-stories-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stories_db
      POSTGRES_USER: ${DB_USER:-stories_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stories_password_123}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    expose:
      - "5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-stories_user} -d stories_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: