#!/bin/bash

# Gmail SMTP 설정 가이드
echo "========================================"
echo "Gmail SMTP 설정 방법"
echo "========================================"
echo ""
echo "1. Gmail 계정에서 2단계 인증 활성화:"
echo "   https://myaccount.google.com/security"
echo ""
echo "2. 앱 비밀번호 생성:"
echo "   https://myaccount.google.com/apppasswords"
echo "   - '메일' 선택"
echo "   - 16자리 앱 비밀번호 복사"
echo ""
echo "3. 서버에서 다음 명령 실행:"
echo ""
echo "ssh -i /Users/jihunkong/Downloads/1001project.pem ubuntu@3.128.143.122"
echo ""
echo "4. .env 파일 수정:"
echo "cd /home/ubuntu/1001-stories"
echo "nano .env"
echo ""
echo "다음 값들을 수정하세요:"
echo "EMAIL_SERVICE_ENABLED=true"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=your-real-email@gmail.com"
echo "SMTP_PASSWORD=your-16-char-app-password"
echo "EMAIL_FROM=noreply@1001stories.org"
echo ""
echo "5. Docker 재시작:"
echo "docker-compose restart app"
echo ""
echo "========================================"