'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { Sparkles, Wand2, ChevronDown, ChevronUp, Loader2, Check, RefreshCw } from 'lucide-react';
import { useTranslation } from '@/lib/i18n/useTranslation';

interface AIReview {
  id: string;
  reviewType: 'GRAMMAR' | 'STRUCTURE' | 'WRITING_HELP';
  feedback: any;
  suggestions: string[];
  score?: number | null;
  createdAt: string;
  isAutoGenerated?: boolean;
  triggerEvent?: string;
  status: string;
}

interface AIReviewCardProps {
  submissionId: string;
}

export default function AIReviewCard({ submissionId }: AIReviewCardProps) {
  const { t } = useTranslation();

  const REVIEW_TYPE_LABELS = useMemo(() => ({
    GRAMMAR: t('dashboard.writer.submitText.aiFeedback.grammar'),
    STRUCTURE: t('dashboard.writer.submitText.aiFeedback.structure'),
    WRITING_HELP: t('dashboard.writer.submitText.aiFeedback.writingHelp')
  }), [t]);

  const [reviews, setReviews] = useState<AIReview[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expandedReview, setExpandedReview] = useState<string | null>(null);
  const [pollingInterval, setPollingInterval] = useState<NodeJS.Timeout | null>(null);

  const startPolling = useCallback(() => {
    setPollingInterval((prevInterval) => {
      if (prevInterval) {
        clearInterval(prevInterval);
      }

      setIsGenerating(true);
      let attempts = 0;
      const maxAttempts = 20;

      const interval = setInterval(async () => {
        attempts++;
        try {
          const response = await fetch(`/api/text-submissions/${submissionId}/ai-reviews`);
          if (!response.ok) {
            throw new Error('Failed to fetch AI reviews');
          }

          const data = await response.json();
          const completedReviews = data.reviews?.filter((r: AIReview) => r.status === 'COMPLETED') || [];

          setReviews(data.reviews || []);

          if (completedReviews.length >= 3 || attempts >= maxAttempts) {
            clearInterval(interval);
            setPollingInterval(null);
            setIsGenerating(false);

            setExpandedReview((prevExpanded) => {
              if (!prevExpanded && completedReviews.length > 0) {
                return completedReviews[0].id;
              }
              return prevExpanded;
            });
          }
        } catch (err) {
          // Polling error - will retry or fail after max attempts
          if (attempts >= maxAttempts) {
            clearInterval(interval);
            setPollingInterval(null);
            setIsGenerating(false);
          }
        }
      }, 3000);

      return interval;
    });
  }, [submissionId]);

  useEffect(() => {
    const checkAndStartPolling = async () => {
      try {
        const response = await fetch(`/api/text-submissions/${submissionId}/ai-reviews`);
        if (response.ok) {
          const data = await response.json();
          setReviews(data.reviews || []);
          setIsLoading(false);

          if (data.reviews && data.reviews.length > 0) {
            setExpandedReview(data.reviews[0].id);

            const completedCount = data.reviews.filter((r: AIReview) => r.status === 'COMPLETED').length;
            if (completedCount < 3 && completedCount >= 0) {
              startPolling();
            }
          }
        } else {
          setIsLoading(false);
        }
      } catch (err) {
        // Error checking reviews
        setIsLoading(false);
      }
    };

    checkAndStartPolling();
    return () => {
      if (pollingInterval) {
        clearInterval(pollingInterval);
      }
    };
  }, [submissionId, startPolling, pollingInterval]);

  const fetchAutoReviews = async (shouldStartPolling = false) => {
    try {
      setIsLoading(true);
      const response = await fetch(`/api/text-submissions/${submissionId}/ai-reviews`);

      if (!response.ok) {
        throw new Error('Failed to fetch AI reviews');
      }

      const data = await response.json();
      setReviews(data.reviews || []);

      if (data.reviews && data.reviews.length > 0) {
        setExpandedReview(data.reviews[0].id);
      }

      if (shouldStartPolling && data.reviews) {
        const completedCount = data.reviews.filter((r: AIReview) => r.status === 'COMPLETED').length;
        if (completedCount < 3) {
          startPolling();
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load AI reviews');
    } finally {
      setIsLoading(false);
    }
  };

  const handleRegenerateReviews = async () => {
    try {
      setIsRegenerating(true);
      setError(null);

      const response = await fetch(`/api/text-submissions/${submissionId}/ai-reviews`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'regenerate' })
      });

      if (!response.ok) {
        throw new Error('Failed to regenerate AI reviews');
      }

      setIsRegenerating(false);
      await fetchAutoReviews(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to regenerate AI reviews');
      setIsRegenerating(false);
    }
  };

  const completedReviews = reviews.filter(r => r.status === 'COMPLETED');

  const uniqueReviews = completedReviews.reduce((acc, review) => {
    const existing = acc.find(r => r.reviewType === review.reviewType);
    if (!existing || new Date(review.createdAt) > new Date(existing.createdAt)) {
      return [...acc.filter(r => r.reviewType !== review.reviewType), review];
    }
    return acc;
  }, [] as AIReview[]);

  const hasAutoReviews = uniqueReviews.some(r => r.isAutoGenerated);

  if (isLoading) {
    return (
      <div className="bg-white border border-[#E5E5EA] rounded-lg p-6">
        <div className="flex items-center justify-center gap-2 py-4">
          <Loader2 className="h-5 w-5 text-[#5951E7] animate-spin" />
          <span className="text-[#8E8E93]" style={{
            fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
            fontSize: '14px'
          }}>
            Loading AI feedback...
          </span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-white border border-[#E5E5EA] rounded-lg p-6">
        <div className="bg-red-50 border border-red-200 rounded-md p-3">
          <p className="text-sm text-red-700">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white border border-[#E5E5EA] rounded-lg p-6">
      <div className="flex flex-col gap-4">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div className="flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-[#5951E7]" />
            <h3 style={{
              fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
              fontSize: '20px',
              fontWeight: 500,
              lineHeight: '1.221',
              color: '#141414'
            }}>
              {t('dashboard.writer.submitText.aiFeedback.title')}
            </h3>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            {hasAutoReviews && (
              <div className="bg-[#EEF2FF] px-3 py-1 rounded-full flex items-center gap-1 whitespace-nowrap">
                <Check className="h-4 w-4 text-[#5951E7]" />
                <span style={{
                  fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                  fontSize: '12px',
                  fontWeight: 500,
                  color: '#5951E7'
                }}>
                  {t('dashboard.writer.submitText.aiFeedback.autoGenerated')}
                </span>
              </div>
            )}
            {uniqueReviews.length > 0 && (
              <button
                onClick={handleRegenerateReviews}
                disabled={isRegenerating}
                className="flex items-center gap-2 px-3 py-1.5 bg-white border border-[#5951E7] text-[#5951E7] rounded-md hover:bg-[#EEF2FF] transition-colors disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                style={{
                  fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                  fontSize: '14px',
                  fontWeight: 500
                }}
              >
                <RefreshCw className={`h-4 w-4 ${isRegenerating ? 'animate-spin' : ''}`} />
                {isRegenerating ? t('dashboard.writer.submitText.aiFeedback.regenerating') : t('dashboard.writer.submitText.aiFeedback.regenerate')}
              </button>
            )}
          </div>
        </div>

        <p style={{
          fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
          fontSize: '16px',
          fontWeight: 400,
          lineHeight: '1.193',
          color: '#8E8E93'
        }}>
          Your draft has been automatically reviewed. Check the feedback below to improve your story.
        </p>

        {isGenerating && (
          <div className="bg-[#EEF2FF] border border-[#E0E7FF] rounded-lg p-4 mb-4">
            <div className="flex items-center gap-3">
              <Loader2 className="h-5 w-5 text-[#5951E7] animate-spin" />
              <div>
                <p className="font-medium text-[#5951E7]" style={{
                  fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                  fontSize: '14px'
                }}>
                  {t('dashboard.writer.submitText.aiFeedback.analyzing')}
                </p>
                <p className="text-sm text-[#8E8E93]" style={{
                  fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                  fontSize: '12px'
                }}>
                  {t('dashboard.writer.submitText.aiFeedback.analysisTime')}
                </p>
              </div>
            </div>
          </div>
        )}

        {uniqueReviews.length === 0 ? (
          <div className="bg-[#F9FAFB] rounded-md p-6 text-center">
            <Sparkles className="h-12 w-12 text-[#8E8E93] mx-auto mb-3" />
            <p style={{
              fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
              fontSize: '14px',
              color: '#8E8E93'
            }}>
              {t('dashboard.writer.submitText.aiFeedback.willAppear')}
            </p>
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            {uniqueReviews.map((review) => (
              <div key={review.id} className="border border-[#E5E5EA] rounded-lg overflow-hidden">
                <button
                  onClick={() => setExpandedReview(expandedReview === review.id ? null : review.id)}
                  className="w-full bg-white hover:bg-[#F9FAFB] py-3 px-4 transition-colors flex items-center justify-between"
                >
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-[#5951E7]" />
                    <span style={{
                      fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                      fontSize: '16px',
                      fontWeight: 500,
                      lineHeight: '1.221',
                      color: '#141414'
                    }}>
                      {REVIEW_TYPE_LABELS[review.reviewType]}
                    </span>
                    {review.score !== undefined && review.score !== null && (
                      <span style={{
                        fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                        fontSize: '14px',
                        fontWeight: 500,
                        color: review.score >= 80 ? '#065F46' : review.score >= 60 ? '#92400E' : '#C2410C'
                      }}>
                        ({review.score}/100)
                      </span>
                    )}
                  </div>
                  {expandedReview === review.id ? (
                    <ChevronUp className="h-5 w-5 text-[#5951E7]" />
                  ) : (
                    <ChevronDown className="h-5 w-5 text-[#5951E7]" />
                  )}
                </button>

                {expandedReview === review.id && (
                  <div className="bg-[#F9FAFB] p-4 border-t border-[#E5E5EA]">
                    {review.feedback?.summary && (
                      <div className="mb-4">
                        <h4 style={{
                          fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                          fontSize: '14px',
                          fontWeight: 500,
                          color: '#141414',
                          marginBottom: '8px'
                        }}>
                          {t('dashboard.writer.submitText.aiFeedback.summary')}
                        </h4>
                        <p style={{
                          fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                          fontSize: '14px',
                          lineHeight: '1.5',
                          color: '#141414'
                        }}>
                          {review.feedback.summary}
                        </p>
                      </div>
                    )}

                    {review.feedback?.strengths && review.feedback.strengths.length > 0 && (
                      <div className="mb-4">
                        <h4 style={{
                          fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                          fontSize: '14px',
                          fontWeight: 500,
                          color: '#065F46',
                          marginBottom: '8px'
                        }}>
                          {t('dashboard.writer.submitText.aiFeedback.strengths')}
                        </h4>
                        <ul className="space-y-2">
                          {review.feedback.strengths.map((strength: string, index: number) => (
                            <li
                              key={index}
                              className="text-sm pl-4 relative before:content-['✓'] before:absolute before:left-0 before:text-[#065F46]"
                              style={{
                                fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                                fontSize: '14px',
                                lineHeight: '1.5',
                                color: '#141414'
                              }}
                            >
                              {strength}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {review.suggestions && review.suggestions.length > 0 && (
                      <div className="mb-4">
                        <h4 style={{
                          fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                          fontSize: '14px',
                          fontWeight: 500,
                          color: '#92400E',
                          marginBottom: '8px'
                        }}>
                          {t('dashboard.writer.submitText.aiFeedback.suggestions')}
                        </h4>
                        <ul className="space-y-2">
                          {review.suggestions.map((suggestion, index) => (
                            <li
                              key={index}
                              className="text-sm pl-4 relative before:content-['→'] before:absolute before:left-0 before:text-[#5951E7]"
                              style={{
                                fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif',
                                fontSize: '14px',
                                lineHeight: '1.5',
                                color: '#141414'
                              }}
                            >
                              {suggestion}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    <p className="text-xs text-[#AEAEB2] mt-4" style={{
                      fontFamily: '"Helvetica Neue", -apple-system, system-ui, sans-serif'
                    }}>
                      Generated {new Date(review.createdAt).toLocaleString()}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
