import { Worker, Job } from 'bullmq';
import { workerOptions } from '../config';
import { AIReviewJobData } from '../ai-review-queue';
import { checkGrammar, analyzeStructure } from '@/lib/ai/openai';
import { prisma } from '@/lib/prisma';
import { logger } from '@/lib/logger';

async function processAIReview(job: Job<AIReviewJobData>) {
  const { submissionId, content, userId, language } = job.data;
  const startTime = Date.now();

  try {
    await job.updateProgress(10);

    const [grammarResult, structureResult] = await Promise.all([
      checkGrammar(content, language),
      analyzeStructure(content, language),
    ]);

    await job.updateProgress(70);

    const overallScore = Math.round(
      (grammarResult.grammarScore + structureResult.structureScore) / 2
    );

    const aiReview = await prisma.aIReview.create({
      data: {
        submissionId: submissionId,
        reviewType: 'GRAMMAR',
        status: 'COMPLETED',
        feedback: JSON.parse(JSON.stringify({
          grammar: grammarResult,
          structure: structureResult,
        })),
        score: overallScore,
        suggestions: [...grammarResult.suggestions, ...structureResult.suggestions],
        modelUsed: 'gpt-4o-mini',
        processingTime: Date.now() - startTime,
        isAutoGenerated: job.data.triggerType === 'auto',
        triggerEvent: job.data.triggerType === 'auto' ? 'AUTO_ON_SAVE' : 'MANUAL_REQUEST',
      },
    });

    await job.updateProgress(90);

    await job.updateProgress(100);

    return {
      success: true,
      reviewId: aiReview.id,
      grammarScore: grammarResult.grammarScore,
      structureScore: structureResult.structureScore,
      overallScore: overallScore,
    };
  } catch (error) {
    throw new Error(
      `Failed to process AI review for submission ${submissionId}: ${
        error instanceof Error ? error.message : 'Unknown error'
      }`
    );
  }
}

let _worker: Worker<AIReviewJobData> | null = null;

export function initAIReviewWorker(): Worker<AIReviewJobData> {
  if (_worker) return _worker;

  _worker = new Worker<AIReviewJobData>(
    'ai-review',
    processAIReview,
    workerOptions
  );

  _worker.on('completed', (job) => {
    logger.info('AI Review Worker: Job completed successfully', { jobId: job.id });
  });

  _worker.on('failed', (job, err) => {
    logger.error('AI Review Worker: Job failed', { jobId: job?.id, error: err });
  });

  _worker.on('error', (err) => {
    logger.error('AI Review Worker: Worker error', err);
  });

  process.on('SIGTERM', async () => {
    logger.info('AI Review Worker: Received SIGTERM, closing worker');
    await _worker?.close();
    process.exit(0);
  });

  process.on('SIGINT', async () => {
    logger.info('AI Review Worker: Received SIGINT, closing worker');
    await _worker?.close();
    process.exit(0);
  });

  return _worker;
}
