#!/usr/bin/env python3
import csv

# Define all new translation entries
# Format: [key, context, en, ko, es, ar, hi, fr, de, ja, pt, ru, it, zh]
new_translations = [
    # Navigation (10 keys)
    ["nav.aboutUs", "Navigation", "About Us", "소개", "Acerca de", "معلومات عنا", "हमारे बारे में", "À propos", "Über uns", "私たちについて", "Sobre nós", "О нас", "Chi siamo", "关于我们"],
    ["nav.programs", "Navigation", "Programs", "프로그램", "Programas", "البرامج", "कार्यक्रम", "Programmes", "Programme", "プログラム", "Programas", "Программы", "Programmi", "计划"],
    ["nav.getInvolved", "Navigation", "Get Involved", "참여하기", "Participar", "شارك", "शामिल हों", "S'impliquer", "Mitmachen", "参加する", "Participe", "Присоединиться", "Partecipa", "参与"],
    ["nav.signIn", "Navigation", "Sign In", "로그인", "Iniciar sesión", "تسجيل الدخول", "साइन इन करें", "Se connecter", "Anmelden", "サインイン", "Entrar", "Войти", "Accedi", "登录"],
    ["nav.signup", "Navigation", "Sign Up", "회원가입", "Registrarse", "التسجيل", "साइन अप", "S'inscrire", "Registrieren", "サインアップ", "Cadastrar", "Регистрация", "Iscriviti", "注册"],
    ["nav.dashboard", "Navigation", "Dashboard", "대시보드", "Panel", "لوحة التحكم", "डैशबोर्ड", "Tableau de bord", "Dashboard", "ダッシュボード", "Painel", "Панель управления", "Dashboard", "仪表板"],
    ["nav.help", "Navigation", "Help & Support", "도움말", "Ayuda y soporte", "المساعدة والدعم", "सहायता और समर्थन", "Aide et support", "Hilfe & Support", "ヘルプとサポート", "Ajuda e suporte", "Помощь и поддержка", "Aiuto e supporto", "帮助与支持"],
    ["nav.logout", "Navigation", "Log Out", "로그아웃", "Cerrar sesión", "تسجيل الخروج", "लॉग आउट", "Se déconnecter", "Abmelden", "ログアウト", "Sair", "Выйти", "Esci", "登出"],
    ["nav.language", "Navigation", "Language", "언어", "Idioma", "اللغة", "भाषा", "Langue", "Sprache", "言語", "Idioma", "Язык", "Lingua", "语言"],
    ["nav.profile", "Navigation", "My Profile", "내 프로필", "Mi perfil", "ملفي", "मेरी प्रोफ़ाइल", "Mon profil", "Mein Profil", "マイプロフィール", "Meu perfil", "Мой профиль", "Il mio profilo", "我的个人资料"],

    # Hero Section (4 keys)
    ["hero.title", "Hero Section", "Discover, Publish, and Share Stories from Around the World", "전 세계의 이야기를 발견하고 출판하며 공유하세요", "Descubre, publica y comparte historias de todo el mundo", "اكتشف ونشر وشارك قصصًا من جميع أنحاء العالم", "दुनिया भर की कहानियों को खोजें, प्रकाशित करें और साझा करें", "Découvrez, publiez et partagez des histoires du monde entier", "Entdecken, veröffentlichen und teilen Sie Geschichten aus aller Welt", "世界中のストーリーを発見、公開、共有", "Descubra, publique e compartilhe histórias de todo o mundo", "Откройте, опубликуйте и поделитесь историями со всего мира", "Scopri, pubblica e condividi storie da tutto il mondo", "发现、发布和分享来自世界各地的故事"],
    ["hero.subtitle", "Hero Section", "Empowering Children Through Stories", "이야기로 아이들에게 힘을", "Empoderando niños a través de historias", "تمكين الأطفال من خلال القصص", "कहानियों के माध्यम से बच्चों को सशक्त बनाना", "Donner du pouvoir aux enfants par les histoires", "Kinder durch Geschichten stärken", "物語で子どもたちに力を", "Capacitando crianças através de histórias", "Расширяем возможности детей через истории", "Dare potere ai bambini attraverso le storie", "通过故事赋予儿童力量"],
    ["hero.description", "Hero Section", "A global non-profit platform connecting writers, educators, and students through the power of storytelling", "스토리텔링의 힘으로 작가, 교육자, 학생을 연결하는 글로벌 비영리 플랫폼", "Una plataforma global sin fines de lucro que conecta escritores, educadores y estudiantes a través del poder de contar historias", "منصة عالمية غير ربحية تربط الكتاب والمعلمين والطلاب من خلال قوة السرد القصصي", "एक वैश्विक गैर-लाभकारी मंच जो कहानी कहने की शक्ति के माध्यम से लेखकों, शिक्षकों और छात्रों को जोड़ता है", "Une plateforme mondiale à but non lucratif reliant écrivains, éducateurs et étudiants par le pouvoir de la narration", "Eine globale gemeinnützige Plattform, die Autoren, Pädagogen und Studenten durch die Kraft des Geschichtenerzählens verbindet", "ストーリーテリングの力を通じて作家、教育者、学生をつなぐグローバルな非営利プラットフォーム", "Uma plataforma global sem fins lucrativos conectando escritores, educadores e estudantes através do poder de contar histórias", "Глобальная некоммерческая платформа, объединяющая писателей, педагогов и студентов через силу рассказа", "Una piattaforma globale senza scopo di lucro che collega scrittori, educatori e studenti attraverso il potere della narrazione", "全球非营利平台，通过讲故事的力量连接作家、教育者和学生"],
    ["hero.cta", "Hero Section", "Explore Stories", "이야기 탐색", "Explorar historias", "استكشف القصص", "कहानियां देखें", "Explorer les histoires", "Geschichten erkunden", "ストーリーを探索", "Explorar histórias", "Исследовать истории", "Esplora storie", "探索故事"],

    # Features (9 keys - 3 cards with title + description each)
    ["features.discover.title", "Feature Card", "Discover Global Stories", "세계의 이야기 발견", "Descubre historias globales", "اكتشف قصصًا عالمية", "वैश्विक कहानियां खोजें", "Découvrez des histoires mondiales", "Entdecken Sie globale Geschichten", "グローバルストーリーを発見", "Descubra histórias globais", "Откройте глобальные истории", "Scopri storie globali", "发现全球故事"],
    ["features.discover.description", "Feature Card", "Access a rich library of stories from children in underserved communities worldwide", "전 세계 소외된 지역 어린이들의 풍부한 이야기 라이브러리에 액세스", "Accede a una rica biblioteca de historias de niños en comunidades desatendidas en todo el mundo", "الوصول إلى مكتبة غنية من قصص الأطفال في المجتمعات المحرومة في جميع أنحاء العالم", "दुनिया भर में वंचित समुदायों के बच्चों की कहानियों की समृद्ध लाइब्रेरी तक पहुंचें", "Accédez à une riche bibliothèque d'histoires d'enfants dans des communautés mal desservies du monde entier", "Greifen Sie auf eine umfangreiche Bibliothek von Geschichten von Kindern in unterversorgten Gemeinden weltweit zu", "世界中の恵まれないコミュニティの子どもたちからの豊富なストーリーライブラリにアクセス", "Acesse uma rica biblioteca de histórias de crianças em comunidades carentes em todo o mundo", "Получите доступ к богатой библиотеке историй детей из недостаточно обслуживаемых сообществ по всему миру", "Accedi a una ricca biblioteca di storie di bambini in comunità svantaggiate in tutto il mondo", "访问来自世界各地服务不足社区儿童的丰富故事库"],
    ["features.publish.title", "Feature Card", "Publish Your Stories", "이야기 출판", "Publica tus historias", "انشر قصصك", "अपनी कहानियां प्रकाशित करें", "Publiez vos histoires", "Veröffentlichen Sie Ihre Geschichten", "ストーリーを公開", "Publique suas histórias", "Опубликуйте свои истории", "Pubblica le tue storie", "发布你的故事"],
    ["features.publish.description", "Feature Card", "Share your voice with the world through our collaborative publishing platform", "협업 출판 플랫폼을 통해 세계와 당신의 목소리를 공유하세요", "Comparte tu voz con el mundo a través de nuestra plataforma de publicación colaborativa", "شارك صوتك مع العالم من خلال منصتنا للنشر التعاوني", "हमारे सहयोगी प्रकाशन मंच के माध्यम से दुनिया के साथ अपनी आवाज साझा करें", "Partagez votre voix avec le monde via notre plateforme de publication collaborative", "Teilen Sie Ihre Stimme mit der Welt über unsere kollaborative Veröffentlichungsplattform", "コラボレーティブな出版プラットフォームを通じてあなたの声を世界と共有", "Compartilhe sua voz com o mundo através de nossa plataforma de publicação colaborativa", "Поделитесь своим голосом с миром через нашу совместную издательскую платформу", "Condividi la tua voce con il mondo attraverso la nostra piattaforma di pubblicazione collaborativa", "通过我们的协作出版平台与世界分享你的声音"],
    ["features.learning.title", "Feature Card", "AI-Enhanced Learning", "AI 강화 학습", "Aprendizaje mejorado con IA", "التعلم المعزز بالذكاء الاصطناعي", "एआई-संवर्धित शिक्षण", "Apprentissage amélioré par l'IA", "KI-verstärktes Lernen", "AI強化学習", "Aprendizado aprimorado por IA", "Обучение с помощью ИИ", "Apprendimento potenziato dall'IA", "AI增强学习"],
    ["features.learning.description", "Feature Card", "Interactive word explanations and content parsing for better understanding", "더 나은 이해를 위한 대화형 단어 설명 및 콘텐츠 분석", "Explicaciones interactivas de palabras y análisis de contenido para una mejor comprensión", "شرح تفاعلي للكلمات وتحليل المحتوى لفهم أفضل", "बेहतर समझ के लिए इंटरैक्टिव शब्द व्याख्या और सामग्री पार्सिंग", "Explications de mots interactives et analyse de contenu pour une meilleure compréhension", "Interaktive Worterklärungen und Inhaltsanalyse für besseres Verständnis", "より良い理解のためのインタラクティブな単語説明とコンテンツ解析", "Explicações interativas de palavras e análise de conteúdo para melhor compreensão", "Интерактивные объяснения слов и анализ контента для лучшего понимания", "Spiegazioni interattive delle parole e analisi dei contenuti per una migliore comprensione", "互动词汇解释和内容解析，帮助更好理解"],

    # Programs (9 keys - 3 cards)
    ["programs.empowerment.title", "Program Card", "Seeds of Empowerment", "역량 강화의 씨앗", "Semillas de empoderamiento", "بذور التمكين", "सशक्तिकरण के बीज", "Graines d'autonomisation", "Samen der Ermächtigung", "エンパワーメントの種", "Sementes de empoderamento", "Семена расширения возможностей", "Semi di empowerment", "赋权之种"],
    ["programs.empowerment.description", "Program Card", "Supporting children in underserved communities through education and storytelling", "교육과 스토리텔링을 통해 소외된 지역 어린이들을 지원", "Apoyando a niños en comunidades desatendidas a través de la educación y la narración de historias", "دعم الأطفال في المجتمعات المحرومة من خلال التعليم والسرد القصصي", "शिक्षा और कहानी कहने के माध्यम से वंचित समुदायों के बच्चों का समर्थन", "Soutenir les enfants dans les communautés mal desservies par l'éducation et la narration", "Unterstützung von Kindern in unterversorgten Gemeinden durch Bildung und Geschichtenerzählen", "教育とストーリーテリングを通じて恵まれないコミュニティの子どもたちをサポート", "Apoiando crianças em comunidades carentes através da educação e contação de histórias", "Поддержка детей в недостаточно обслуживаемых сообществах через образование и рассказывание историй", "Sostenere i bambini nelle comunità svantaggiate attraverso l'istruzione e la narrazione", "通过教育和讲故事支持服务不足社区的儿童"],
    ["programs.diversity.title", "Program Card", "Global Diversity Initiative", "글로벌 다양성 이니셔티브", "Iniciativa de diversidad global", "مبادرة التنوع العالمي", "वैश्विक विविधता पहल", "Initiative de diversité mondiale", "Globale Diversitätsinitiative", "グローバル多様性イニシアチブ", "Iniciativa de diversidade global", "Инициатива глобального разнообразия", "Iniziativa di diversità globale", "全球多样性倡议"],
    ["programs.diversity.description", "Program Card", "Celebrating diverse voices and perspectives from every corner of the world", "세계 모든 곳의 다양한 목소리와 관점을 축하", "Celebrando voces y perspectivas diversas de todos los rincones del mundo", "الاحتفال بالأصوات والوجهات النظر المتنوعة من كل ركن من أركان العالم", "दुनिया के हर कोने से विविध आवाज़ों और दृष्टिकोणों का जश्न", "Célébrer des voix et perspectives diverses de tous les coins du monde", "Feier verschiedener Stimmen und Perspektiven aus allen Ecken der Welt", "世界中のあらゆる場所からの多様な声と視点を祝う", "Celebrando vozes e perspectivas diversas de todos os cantos do mundo", "Празднование разнообразных голосов и перспектив со всех уголков мира", "Celebrare voci e prospettive diverse da ogni angolo del mondo", "庆祝来自世界各个角落的多样化声音和观点"],
    ["programs.english.title", "Program Card", "English Language Learning", "영어 학습", "Aprendizaje del idioma inglés", "تعلم اللغة الإنجليزية", "अंग्रेजी भाषा सीखना", "Apprentissage de l'anglais", "Englisch lernen", "英語学習", "Aprendizado de inglês", "Изучение английского языка", "Apprendimento della lingua inglese", "英语学习"],
    ["programs.english.description", "Program Card", "Interactive stories designed for English language learners", "영어 학습자를 위해 설계된 대화형 이야기", "Historias interactivas diseñadas para estudiantes de inglés", "قصص تفاعلية مصممة لمتعلمي اللغة الإنجليزية", "अंग्रेजी भाषा सीखने वालों के लिए डिज़ाइन की गई इंटरैक्टिव कहानियां", "Histoires interactives conçues pour les apprenants en anglais", "Interaktive Geschichten für Englischlernende", "英語学習者向けのインタラクティブストーリー", "Histórias interativas projetadas para estudantes de inglês", "Интерактивные истории для изучающих английский", "Storie interattive progettate per studenti di inglese", "为英语学习者设计的互动故事"],

    # Footer CTA (4 keys)
    ["footer.cta.title", "Footer CTA", "Join Our Global Community", "글로벌 커뮤니티에 참여", "Únete a nuestra comunidad global", "انضم إلى مجتمعنا العالمي", "हमारे वैश्विक समुदाय में शामिل हों", "Rejoignez notre communauté mondiale", "Treten Sie unserer globalen Gemeinschaft bei", "グローバルコミュニティに参加", "Junte-se à nossa comunidade global", "Присоединяйтесь к нашему глобальному сообществу", "Unisciti alla nostra comunità globale", "加入我们的全球社区"],
    ["footer.cta.description", "Footer CTA", "Start discovering, creating, and sharing stories today", "오늘부터 이야기를 발견하고 만들고 공유하세요", "Comienza a descubrir, crear y compartir historias hoy", "ابدأ في اكتشاف وإنشاء ومشاركة القصص اليوم", "आज ही कहानियों की खोज, निर्माण और साझा करना शुरू करें", "Commencez à découvrir, créer et partager des histoires aujourd'hui", "Beginnen Sie heute Geschichten zu entdecken, zu erstellen und zu teilen", "今日からストーリーを発見、作成、共有しましょう", "Comece a descobrir, criar e compartilhar histórias hoje", "Начните открывать, создавать и делиться историями сегодня", "Inizia a scoprire, creare e condividere storie oggi", "今天开始发现、创建和分享故事"],
    ["footer.cta.primary", "Footer CTA", "Get Started", "시작하기", "Empezar", "ابدأ", "शुरू करें", "Commencer", "Loslegen", "始める", "Começar", "Начать", "Inizia", "开始"],
    ["footer.cta.secondary", "Footer CTA", "Learn More", "자세히 알아보기", "Más información", "اعرف المزيد", "और जानें", "En savoir plus", "Mehr erfahren", "もっと詳しく", "Saiba mais", "Узнать больше", "Scopri di più", "了解更多"],
]

# Add About page translations (41 keys)
about_translations = [
    # About Hero (3 keys)
    ["about.hero.title", "About Page", "Our Mission: Empowering Children Through Stories", "우리의 사명: 이야기로 아이들에게 힘을", "Nuestra misión: Empoderar a los niños a través de historias", "مهمتنا: تمكين الأطفال من خلال القصص", "हमारा मिशन: कहानियों के माध्यम से बच्चों को सशक्त बनाना", "Notre mission: Donner du pouvoir aux enfants par les histoires", "Unsere Mission: Kinder durch Geschichten stärken", "私たちの使命: 物語で子どもたちに力を", "Nossa missão: Capacitar crianças através de histórias", "Наша миссия: Расширять возможности детей через истории", "La nostra missione: Dare potere ai bambini attraverso le storie", "我们的使命：通过故事赋予儿童力量"],
    ["about.hero.subtitle", "About Page", "Connecting voices from underserved communities with the world", "소외된 지역의 목소리를 세계와 연결", "Conectando voces de comunidades desatendidas con el mundo", "ربط أصوات المجتمعات المحرومة بالعالم", "वंचित समुदायों की आवाज़ों को दुनिया से जोड़ना", "Connecter les voix des communautés mal desservies avec le monde", "Stimmen aus unterversorgten Gemeinden mit der Welt verbinden", "恵まれないコミュニティの声を世界とつなぐ", "Conectando vozes de comunidades carentes com o mundo", "Соединяя голоса недостаточно обслуживаемых сообществ с миром", "Collegare le voci delle comunità svantaggiate con il mondo", "将服务不足社区的声音与世界联系起来"],
    ["about.hero.scroll", "About Page", "Scroll to learn more", "스크롤하여 자세히 알아보기", "Desplázate para saber más", "مرر لمعرفة المزيد", "और जानने के लिए स्क्रॉल करें", "Faites défiler pour en savoir plus", "Scrollen Sie, um mehr zu erfahren", "スクロールして詳細を確認", "Role para saber mais", "Прокрутите, чтобы узнать больше", "Scorri per saperne di più", "滚动了解更多"],

    # About Content (10 keys)
    ["about.content.vision.title", "About Page", "Our Vision", "우리의 비전", "Nuestra visión", "رؤيتنا", "हमारी दृष्टि", "Notre vision", "Unsere Vision", "私たちのビジョン", "Nossa visão", "Наше видение", "La nostra visione", "我们的愿景"],
    ["about.content.vision.text", "About Page", "We believe every child has a story worth sharing. 1001 Stories is a global non-profit platform dedicated to discovering, publishing, and sharing stories from children in underserved communities.", "모든 어린이에게는 공유할 가치가 있는 이야기가 있다고 믿습니다. 1001 Stories는 소외된 지역 어린이들의 이야기를 발견하고 출판하며 공유하는 데 전념하는 글로벌 비영리 플랫폼입니다.", "Creemos que cada niño tiene una historia que vale la pena compartir. 1001 Stories es una plataforma global sin fines de lucro dedicada a descubrir, publicar y compartir historias de niños en comunidades desatendidas.", "نؤمن بأن كل طفل لديه قصة تستحق المشاركة. 1001 Stories هي منصة عالمية غير ربحية مكرسة لاكتشاف ونشر ومشاركة قصص الأطفال في المجتمعات المحرومة.", "हम मानते हैं कि हर बच्चे के पास साझा करने लायक एक कहानी है। 1001 Stories एक वैश्विक गैर-लाभकारी मंच है जो वंचित समुदायों के बच्चों की कहानियों को खोजने, प्रकाशित करने और साझा करने के लिए समर्पित है।", "Nous croyons que chaque enfant a une histoire qui vaut la peine d'être partagée. 1001 Stories est une plateforme mondiale à but non lucratif dédiée à la découverte, à la publication et au partage d'histoires d'enfants dans des communautés mal desservies.", "Wir glauben, dass jedes Kind eine Geschichte hat, die es wert ist, geteilt zu werden. 1001 Stories ist eine globale gemeinnützige Plattform, die sich der Entdeckung, Veröffentlichung und dem Teilen von Geschichten von Kindern in unterversorgten Gemeinden widmet.", "すべての子どもには共有する価値のある物語があると信じています。1001 Storiesは、恵まれないコミュニティの子どもたちの物語を発見、出版、共有することに専念するグローバルな非営利プラットフォームです。", "Acreditamos que toda criança tem uma história que vale a pena compartilhar. 1001 Stories é uma plataforma global sem fins lucrativos dedicada a descobrir, publicar e compartilhar histórias de crianças em comunidades carentes.", "Мы верим, что у каждого ребенка есть история, достойная того, чтобы ею поделиться. 1001 Stories - это глобальная некоммерческая платформа, посвященная открытию, публикации и обмену историями детей из недостаточно обслуживаемых сообществ.", "Crediamo che ogni bambino abbia una storia che vale la pena condividere. 1001 Stories è una piattaforma globale senza scopo di lucro dedicata a scoprire, pubblicare e condividere storie di bambini in comunità svantaggiate.", "我们相信每个孩子都有值得分享的故事。1001 Stories是一个全球非营利平台，致力于发现、发布和分享来自服务不足社区儿童的故事。"],
    ["about.content.impact.title", "About Page", "Our Impact", "우리의 영향", "Nuestro impacto", "تأثيرنا", "हमारा प्रभाव", "Notre impact", "Unsere Wirkung", "私たちの影響", "Nosso impacto", "Наше влияние", "Il nostro impatto", "我们的影响"],
    ["about.content.impact.text", "About Page", "Through our Seeds of Empowerment program, we reinvest all revenue back into supporting children's education and creative expression in underserved communities worldwide.", "Seeds of Empowerment 프로그램을 통해 우리는 모든 수익을 전 세계 소외된 지역 어린이들의 교육과 창의적 표현을 지원하는 데 재투자합니다.", "A través de nuestro programa Seeds of Empowerment, reinvertimos todos los ingresos en el apoyo a la educación y la expresión creativa de los niños en comunidades desatendidas en todo el mundo.", "من خلال برنامج Seeds of Empowerment، نعيد استثمار جميع الإيرادات في دعم تعليم الأطفال والتعبير الإبداعي في المجتمعات المحرومة في جميع أنحاء العالم.", "हमारे Seeds of Empowerment कार्यक्रम के माध्यम से, हम सभी राजस्व को दुनिया भर के वंचित समुदायों में बच्चों की शिक्षा और रचनात्मक अभिव्यक्ति का समर्थन करने में पुनर्निवेश करते हैं।", "Grâce à notre programme Seeds of Empowerment, nous réinvestissons tous les revenus pour soutenir l'éducation et l'expression créative des enfants dans les communautés mal desservies du monde entier.", "Durch unser Seeds of Empowerment-Programm investieren wir alle Einnahmen zurück in die Unterstützung der Bildung und des kreativen Ausdrucks von Kindern in unterversorgten Gemeinden weltweit.", "Seeds of Empowermentプログラムを通じて、世界中の恵まれないコミュニティにおける子どもたちの教育と創造的表現の支援にすべての収益を再投資しています。", "Através do nosso programa Seeds of Empowerment, reinvestimos toda a receita no apoio à educação e expressão criativa das crianças em comunidades carentes em todo o mundo.", "Через нашу программу Seeds of Empowerment мы реинвестируем все доходы в поддержку образования и творческого самовыражения детей в недостаточно обслуживаемых сообществах по всему миру.", "Attraverso il nostro programma Seeds of Empowerment, reinvestiamo tutti i ricavi nel supporto all'istruzione e all'espressione creativa dei bambini nelle comunità svantaggiate in tutto il mondo.", "通过我们的赋权之种计划，我们将所有收入重新投资于支持全球服务不足社区儿童的教育和创意表达。"],
    ["about.content.platform.title", "About Page", "Our Platform", "우리 플랫폼", "Nuestra plataforma", "منصتنا", "हमारा मंच", "Notre plateforme", "Unsere Plattform", "私たちのプラットフォーム", "Nossa plataforma", "Наша платформа", "La nostra piattaforma", "我们的平台"],
    ["about.content.platform.text", "About Page", "1001 Stories connects writers, educators, and students through an innovative multi-role system that facilitates discovery, learning, and creative expression.", "1001 Stories는 발견, 학습, 창의적 표현을 촉진하는 혁신적인 다중 역할 시스템을 통해 작가, 교육자, 학생을 연결합니다.", "1001 Stories conecta a escritores, educadores y estudiantes a través de un innovador sistema de múltiples roles que facilita el descubrimiento, el aprendizaje y la expresión creativa.", "يربط 1001 Stories الكتاب والمعلمين والطلاب من خلال نظام مبتكر متعدد الأدوار يسهل الاكتشاف والتعلم والتعبير الإبداعي.", "1001 Stories एक नवीन बहु-भूमिका प्रणाली के माध्यम से लेखकों, शिक्षकों और छात्रों को जोड़ता है जो खोज, सीखने और रचनात्मक अभिव्यक्ति को सुविधाजनक बनाती है।", "1001 Stories connecte les écrivains, les éducateurs et les étudiants grâce à un système innovant à rôles multiples qui facilite la découverte, l'apprentissage et l'expression créative.", "1001 Stories verbindet Autoren, Pädagogen und Studenten durch ein innovatives Multi-Rollen-System, das Entdeckung, Lernen und kreativen Ausdruck erleichtert.", "1001 Storiesは、発見、学習、創造的表現を促進する革新的なマルチロールシステムを通じて、作家、教育者、学生をつなぎます。", "1001 Stories conecta escritores, educadores e estudantes através de um sistema inovador de múltiplos papéis que facilita a descoberta, aprendizagem e expressão criativa.", "1001 Stories соединяет писателей, педагогов и студентов через инновационную многоролевую систему, которая способствует открытию, обучению и творческому самовыражению.", "1001 Stories collega scrittori, educatori e studenti attraverso un innovativo sistema multi-ruolo che facilita la scoperta, l'apprendimento e l'espressione creativa.", "1001 Stories通过创新的多角色系统连接作家、教育者和学生，促进发现、学习和创意表达。"],
    ["about.content.technology.title", "About Page", "AI-Enhanced Learning", "AI 강화 학습", "Aprendizaje mejorado con IA", "التعلم المعزز بالذكاء الاصطناعي", "एआई-संवर्धित शिक्षण", "Apprentissage amélioré par l'IA", "KI-verstärktes Lernen", "AI強化学習", "Aprendizado aprimorado por IA", "Обучение с помощью ИИ", "Apprendimento potenziato dall'IA", "AI增强学习"],
    ["about.content.technology.text", "About Page", "Our platform leverages AI technology to provide interactive word explanations, content parsing, and educational assistance, making stories more accessible and engaging for learners worldwide.", "우리 플랫폼은 AI 기술을 활용하여 대화형 단어 설명, 콘텐츠 분석, 교육 지원을 제공하여 전 세계 학습자들에게 이야기를 더 접근 가능하고 매력적으로 만듭니다.", "Nuestra plataforma aprovecha la tecnología de IA para proporcionar explicaciones interactivas de palabras, análisis de contenido y asistencia educativa, haciendo que las historias sean más accesibles y atractivas para los estudiantes de todo el mundo.", "تستفيد منصتنا من تكنولوجيا الذكاء الاصطناعي لتوفير شرح تفاعلي للكلمات وتحليل المحتوى والمساعدة التعليمية، مما يجعل القصص أكثر سهولة وجاذبية للمتعلمين في جميع أنحاء العالم.", "हमारा मंच इंटरैक्टिव शब्द व्याख्या, सामग्री पार्सिंग और शैक्षिक सहायता प्रदान करने के लिए एआई तकनीक का लाभ उठाता है, जिससे दुनिया भर के शिक्षार्थियों के लिए कहानियां अधिक सुलभ और आकर्षक बन जाती हैं।", "Notre plateforme exploite la technologie de l'IA pour fournir des explications de mots interactives, une analyse de contenu et une assistance éducative, rendant les histoires plus accessibles et engageantes pour les apprenants du monde entier.", "Unsere Plattform nutzt KI-Technologie, um interaktive Worterklärungen, Inhaltsanalyse und pädagogische Unterstützung bereitzustellen, wodurch Geschichten für Lernende weltweit zugänglicher und ansprechender werden.", "私たちのプラットフォームはAI技術を活用して、インタラクティブな単語説明、コンテンツ解析、教育支援を提供し、世界中の学習者にとってストーリーをよりアクセスしやすく魅力的なものにします。", "Nossa plataforma aproveita a tecnologia de IA para fornecer explicações interativas de palavras, análise de conteúdo e assistência educacional, tornando as histórias mais acessíveis e envolventes para aprendizes em todo o mundo.", "Наша платформа использует технологию ИИ для предоставления интерактивных объяснений слов, анализа контента и образовательной помощи, делая истории более доступными и привлекательными для учащихся по всему миру.", "La nostra piattaforma sfrutta la tecnologia AI per fornire spiegazioni interattive delle parole, analisi dei contenuti e assistenza educativa, rendendo le storie più accessibili e coinvolgenti per gli studenti di tutto il mondo.", "我们的平台利用AI技术提供互动词汇解释、内容解析和教育辅助，使故事对全球学习者更加可及和吸引人。"],
    ["about.content.community.title", "About Page", "Our Community", "우리 커뮤니티", "Nuestra comunidad", "مجتمعنا", "हमारा समुदाय", "Notre communauté", "Unsere Gemeinschaft", "私たちのコミュニティ", "Nossa comunidade", "Наше сообщество", "La nostra comunità", "我们的社区"],
    ["about.content.community.text", "About Page", "Join a global network of storytellers, educators, and learners committed to celebrating diversity and empowering the next generation through the power of stories.", "이야기의 힘으로 다양성을 축하하고 다음 세대에 힘을 실어주기 위해 헌신하는 스토리텔러, 교육자, 학습자들의 글로벌 네트워크에 참여하세요.", "Únete a una red global de narradores, educadores y estudiantes comprometidos con celebrar la diversidad y empoderar a la próxima generación a través del poder de las historias.", "انضم إلى شبكة عالمية من رواة القصص والمعلمين والمتعلمين الملتزمين بالاحتفال بالتنوع وتمكين الجيل القادم من خلال قوة القصص.", "विविधता का जश्न मनाने और कहानियों की शक्ति के माध्यम से अगली पीढ़ी को सशक्त बनाने के लिए प्रतिबद्ध कहानीकारों, शिक्षकों और शिक्षार्थियों के वैश्विक नेटवर्क में शामिल हों।", "Rejoignez un réseau mondial de conteurs, d'éducateurs et d'apprenants engagés à célébrer la diversité et à autonomiser la prochaine génération par le pouvoir des histoires.", "Treten Sie einem globalen Netzwerk von Geschichtenerzählern, Pädagogen und Lernenden bei, die sich dafür einsetzen, Vielfalt zu feiern und die nächste Generation durch die Kraft von Geschichten zu stärken.", "物語の力を通じて多様性を祝い、次世代に力を与えることに尽力するストーリーテラー、教育者、学習者のグローバルネットワークに参加しましょう。", "Junte-se a uma rede global de contadores de histórias, educadores e aprendizes comprometidos em celebrar a diversidade e capacitar a próxima geração através do poder das histórias.", "Присоединяйтесь к глобальной сети рассказчиков, педагогов и учащихся, стремящихся отмечать разнообразие и расширять возможности следующего поколения через силу историй.", "Unisciti a una rete globale di narratori, educatori e studenti impegnati a celebrare la diversità e a dare potere alla prossima generazione attraverso il potere delle storie.", "加入一个致力于庆祝多样性并通过故事的力量赋予下一代能力的全球讲故事者、教育者和学习者网络。"],

    # About Testimonials (6 keys - 2 testimonials)
    ["about.testimonial1.quote", "About Page", "1001 Stories has transformed how we approach literacy in our classroom. The diverse collection of voices helps students see themselves in the stories.", "1001 Stories는 우리가 교실에서 문해력에 접근하는 방식을 변화시켰습니다. 다양한 목소리 모음은 학생들이 이야기 속에서 자신을 볼 수 있도록 돕습니다.", "1001 Stories ha transformado la forma en que abordamos la alfabetización en nuestro aula. La diversa colección de voces ayuda a los estudiantes a verse a sí mismos en las historias.", "غيّر 1001 Stories الطريقة التي نتعامل بها مع محو الأمية في فصلنا الدراسي. تساعد المجموعة المتنوعة من الأصوات الطلاب على رؤية أنفسهم في القصص.", "1001 Stories ने हमारी कक्षा में साक्षरता के प्रति हमारे दृष्टिकोण को बदल दिया है। आवाज़ों का विविध संग्रह छात्रों को कहानियों में खुद को देखने में मदद करता है।", "1001 Stories a transformé notre approche de l'alphabétisation en classe. La collection diversifiée de voix aide les étudiants à se voir dans les histoires.", "1001 Stories hat verändert, wie wir Alphabetisierung in unserem Klassenzimmer angehen. Die vielfältige Sammlung von Stimmen hilft Schülern, sich selbst in den Geschichten zu sehen.", "1001 Storiesは、私たちの教室での識字へのアプローチを変革しました。多様な声のコレクションは、学生が物語の中で自分自身を見るのに役立ちます。", "1001 Stories transformou como abordamos a alfabetização em nossa sala de aula. A coleção diversificada de vozes ajuda os alunos a se verem nas histórias.", "1001 Stories изменил наш подход к грамотности в классе. Разнообразная коллекция голосов помогает студентам увидеть себя в историях.", "1001 Stories ha trasformato il nostro approccio all'alfabetizzazione in classe. La diversa raccolta di voci aiuta gli studenti a vedersi nelle storie.", "1001 Stories改变了我们在课堂上处理识字的方式。多样化的声音集合帮助学生在故事中看到自己。"],
    ["about.testimonial1.author", "About Page", "Sarah Johnson", "사라 존슨", "Sarah Johnson", "سارة جونسون", "सारा जॉनसन", "Sarah Johnson", "Sarah Johnson", "サラ・ジョンソン", "Sarah Johnson", "Сара Джонсон", "Sarah Johnson", "莎拉·约翰逊"],
    ["about.testimonial1.role", "About Page", "Elementary School Teacher", "초등학교 교사", "Maestra de escuela primaria", "معلمة مدرسة ابتدائية", "प्राथमिक विद्यालय शिक्षक", "Enseignante en école primaire", "Grundschullehrerin", "小学校教師", "Professora de escola primária", "Учитель начальной школы", "Insegnante di scuola elementare", "小学教师"],
    ["about.testimonial2.quote", "About Page", "Being able to share my story and see it published gave me confidence I never knew I had. Now I help other children find their voice too.", "내 이야기를 공유하고 출판된 것을 보니 내가 몰랐던 자신감을 얻었습니다. 이제 다른 아이들도 자신의 목소리를 찾을 수 있도록 돕고 있습니다.", "Poder compartir mi historia y verla publicada me dio una confianza que nunca supe que tenía. Ahora ayudo a otros niños a encontrar su voz también.", "القدرة على مشاركة قصتي ورؤيتها منشورة أعطتني ثقة لم أكن أعلم أنني أمتلكها. الآن أساعد الأطفال الآخرين في العثور على صوتهم أيضًا.", "अपनी कहानी साझा करने और उसे प्रकाशित देखने से मुझे वह आत्मविश्वास मिला जो मुझे पता नहीं था कि मेरे पास है। अब मैं अन्य बच्चों को भी उनकी आवाज़ खोजने में मदद करती हूं।", "Pouvoir partager mon histoire et la voir publiée m'a donné une confiance que je ne savais pas avoir. Maintenant j'aide d'autres enfants à trouver leur voix aussi.", "Die Möglichkeit, meine Geschichte zu teilen und sie veröffentlicht zu sehen, gab mir ein Selbstvertrauen, von dem ich nicht wusste, dass ich es hatte. Jetzt helfe ich auch anderen Kindern, ihre Stimme zu finden.", "私の物語を共有し、それが出版されるのを見ることができたことで、私は自分が持っているとは知らなかった自信を得ました。今では他の子どもたちも自分の声を見つけるのを手伝っています。", "Poder compartilhar minha história e vê-la publicada me deu uma confiança que eu não sabia que tinha. Agora ajudo outras crianças a encontrar sua voz também.", "Возможность поделиться своей историей и увидеть ее опубликованной дала мне уверенность, о которой я не знала, что у меня есть. Теперь я помогаю другим детям найти свой голос тоже.", "Poter condividere la mia storia e vederla pubblicata mi ha dato una fiducia che non sapevo di avere. Ora aiuto anche altri bambini a trovare la loro voce.", "能够分享我的故事并看到它被出版给了我从未知道自己拥有的信心。现在我也帮助其他孩子找到他们的声音。"],
    ["about.testimonial2.author", "About Page", "Maria Gonzalez", "마리아 곤살레스", "María González", "ماريا غونزاليس", "मारिया गोंजालेज", "Maria Gonzalez", "Maria Gonzalez", "マリア・ゴンザレス", "Maria Gonzalez", "Мария Гонсалес", "Maria Gonzalez", "玛丽亚·冈萨雷斯"],
    ["about.testimonial2.role", "About Page", "Student Writer", "학생 작가", "Escritora estudiantil", "كاتبة طالبة", "छात्र लेखक", "Écrivaine étudiante", "Studentische Schriftstellerin", "学生作家", "Escritora estudante", "Студентка-писательница", "Scrittrice studentessa", "学生作家"],

    # About Stats (8 keys - 4 stats)
    ["about.stats.stories.number", "About Page", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+", "10,000+"],
    ["about.stats.stories.label", "About Page", "Stories Published", "출판된 이야기", "Historias publicadas", "قصص منشورة", "प्रकाशित कहानियां", "Histoires publiées", "Veröffentlichte Geschichten", "公開されたストーリー", "Histórias publicadas", "Опубликованные истории", "Storie pubblicate", "已发布故事"],
    ["about.stats.countries.number", "About Page", "50+", "50+", "50+", "50+", "50+", "50+", "50+", "50+", "50+", "50+", "50+", "50+"],
    ["about.stats.countries.label", "About Page", "Countries Represented", "대표 국가", "Países representados", "دول ممثلة", "प्रतिनिधित्व किए गए देश", "Pays représentés", "Vertretene Länder", "代表国", "Países representados", "Представленные страны", "Paesi rappresentati", "代表国家"],
    ["about.stats.students.number", "About Page", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+", "100,000+"],
    ["about.stats.students.label", "About Page", "Students Reached", "도달한 학생", "Estudiantes alcanzados", "طلاب تم الوصول إليهم", "पहुंचे छात्र", "Étudiants atteints", "Erreichte Schüler", "到達した学生", "Alunos alcançados", "Достигнутые студенты", "Studenti raggiunti", "已触及学生"],
    ["about.stats.languages.number", "About Page", "25+", "25+", "25+", "25+", "25+", "25+", "25+", "25+", "25+", "25+", "25+", "25+"],
    ["about.stats.languages.label", "About Page", "Languages Supported", "지원 언어", "Idiomas admitidos", "لغات مدعومة", "समर्थित भाषाएं", "Langues prises en charge", "Unterstützte Sprachen", "サポートされる言語", "Idiomas suportados", "Поддерживаемые языки", "Lingue supportate", "支持的语言"],

    # About Team (6 keys - 2 team members)
    ["about.team.title", "About Page", "Meet Our Team", "우리 팀을 만나보세요", "Conoce a nuestro equipo", "تعرف على فريقنا", "हमारी टीम से मिलें", "Rencontrez notre équipe", "Lernen Sie unser Team kennen", "私たちのチームに会う", "Conheça nossa equipe", "Познакомьтесь с нашей командой", "Incontra il nostro team", "认识我们的团队"],
    ["about.team.member1.name", "About Page", "Dr. Emily Chen", "에밀리 첸 박사", "Dra. Emily Chen", "الدكتورة إميلي تشين", "डॉ. एमिली चेन", "Dr Emily Chen", "Dr. Emily Chen", "エミリー・チェン博士", "Dra. Emily Chen", "Др. Эмили Чен", "Dr. Emily Chen", "陈艾米莉博士"],
    ["about.team.member1.role", "About Page", "Founder & Executive Director", "창립자 및 전무이사", "Fundadora y directora ejecutiva", "المؤسسة والمديرة التنفيذية", "संस्थापक और कार्यकारी निदेशक", "Fondatrice et directrice exécutive", "Gründerin und Geschäftsführerin", "創設者兼エグゼクティブディレクター", "Fundadora e diretora executiva", "Основатель и исполнительный директор", "Fondatrice e direttrice esecutiva", "创始人兼执行董事"],
    ["about.team.member2.name", "About Page", "Michael Okonkwo", "마이클 오콘코", "Michael Okonkwo", "مايكل أوكونكوو", "माइकल ओकोनक्वो", "Michael Okonkwo", "Michael Okonkwo", "マイケル・オコンコ", "Michael Okonkwo", "Майкл Оконко", "Michael Okonkwo", "迈克尔·奥孔科"],
    ["about.team.member2.role", "About Page", "Head of Global Programs", "글로벌 프로그램 책임자", "Director de programas globales", "رئيس البرامج العالمية", "वैश्विक कार्यक्रमों के प्रमुख", "Responsable des programmes mondiaux", "Leiter globale Programme", "グローバルプログラム責任者", "Chefe de programas globais", "Руководитель глобальных программ", "Responsabile programmi globali", "全球计划负责人"],

    # About Footer (4 keys)
    ["about.footer.contact.title", "About Page", "Get in Touch", "연락하기", "Ponerse en contacto", "تواصل معنا", "संपर्क करें", "Contactez-nous", "Kontakt", "お問い合わせ", "Entre em contato", "Связаться", "Contattaci", "联系我们"],
    ["about.footer.contact.email", "About Page", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org", "contact@1001stories.org"],
    ["about.footer.social.title", "About Page", "Follow Us", "팔로우하기", "Síguenos", "تابعنا", "हमें फॉलो करें", "Suivez-nous", "Folgen Sie uns", "フォローする", "Siga-nos", "Подписывайтесь", "Seguici", "关注我们"],
    ["about.footer.newsletter.title", "About Page", "Subscribe to Our Newsletter", "뉴스레터 구독", "Suscríbete a nuestro boletín", "اشترك في نشرتنا الإخبارية", "हमारे न्यूज़लेटर की सदस्यता लें", "Abonnez-vous à notre newsletter", "Abonnieren Sie unseren Newsletter", "ニュースレターを購読", "Inscreva-se em nossa newsletter", "Подпишитесь на нашу рассылку", "Iscriviti alla nostra newsletter", "订阅我们的新闻通讯"],
]

# Add Footer (4 keys)
footer_translations = [
    ["footer.copyright", "Footer", "© 2025 1001 Stories. All rights reserved.", "© 2025 1001 Stories. 모든 권리 보유.", "© 2025 1001 Stories. Todos los derechos reservados.", "© 2025 1001 Stories. جميع الحقوق محفوظة.", "© 2025 1001 Stories. सभी अधिकार सुरक्षित।", "© 2025 1001 Stories. Tous droits réservés.", "© 2025 1001 Stories. Alle Rechte vorbehalten.", "© 2025 1001 Stories. 全著作権所有。", "© 2025 1001 Stories. Todos os direitos reservados.", "© 2025 1001 Stories. Все права защищены.", "© 2025 1001 Stories. Tutti i diritti riservati.", "© 2025 1001 Stories. 保留所有权利。"],
    ["footer.privacy", "Footer", "Privacy Policy", "개인정보 처리방침", "Política de privacidad", "سياسة الخصوصية", "गोपनीयता नीति", "Politique de confidentialité", "Datenschutzrichtlinie", "プライバシーポリシー", "Política de privacidade", "Политика конфиденциальности", "Informativa sulla privacy", "隐私政策"],
    ["footer.terms", "Footer", "Terms of Service", "서비스 약관", "Términos de servicio", "شروط الخدمة", "सेवा की शर्तें", "Conditions d'utilisation", "Nutzungsbedingungen", "利用規約", "Termos de serviço", "Условия обслуживания", "Termini di servizio", "服务条款"],
    ["footer.contact", "Footer", "Contact Us", "문의하기", "Contáctanos", "اتصل بنا", "हमसे संपर्क करें", "Nous contacter", "Kontaktieren Sie uns", "お問い合わせ", "Entre em contato", "Свяжитесь с нами", "Contattaci", "联系我们"],
]

# Add Stories translations (11 keys)
stories_translations = [
    # Tabs (3 keys)
    ["stories.tabs.all", "Tab Label", "All Stories", "모든 이야기", "Todas las historias", "جميع القصص", "सभी कहानियां", "Toutes les histoires", "Alle Geschichten", "すべてのストーリー", "Todas as histórias", "Все истории", "Tutte le storie", "所有故事"],
    ["stories.tabs.submitted", "Tab Label", "Submitted", "제출됨", "Enviado", "مُرسَل", "सबमिट किया गया", "Soumis", "Eingereicht", "提出済み", "Enviado", "Отправлено", "Inviato", "已提交"],
    ["stories.tabs.underReview", "Tab Label", "Under Review", "검토 중", "En revisión", "قيد المراجعة", "समीक्षाधीन", "En révision", "Wird überprüft", "レビュー中", "Em revisão", "На рассмотрении", "In revisione", "审核中"],

    # Status (5 keys)
    ["stories.status.draft", "Status Label", "Draft", "초안", "Borrador", "مسودة", "मसौदा", "Brouillon", "Entwurf", "下書き", "Rascunho", "Черновик", "Bozza", "草稿"],
    ["stories.status.pending", "Status Label", "Pending Review", "검토 대기", "Pendiente de revisión", "في انتظار المراجعة", "समीक्षा लंबित", "En attente de révision", "Überprüfung ausstehend", "レビュー待ち", "Revisão pendente", "Ожидание проверки", "In attesa di revisione", "待审核"],
    ["stories.status.inReview", "Status Label", "In Review", "검토 중", "En revisión", "قيد المراجعة", "समीक्षाधीन", "En révision", "Wird überprüft", "レビュー中", "Em revisão", "На рассмотрении", "In revisione", "审核中"],
    ["stories.status.needsRevision", "Status Label", "Needs Revision", "수정 필요", "Necesita revisión", "يحتاج إلى مراجعة", "संशोधन की आवश्यकता", "Nécessite une révision", "Überarbeitung erforderlich", "修正が必要", "Precisa de revisão", "Требует доработки", "Richiede revisione", "需要修改"],
    ["stories.status.approved", "Status Label", "Approved", "승인됨", "Aprobado", "موافق عليه", "स्वीकृत", "Approuvé", "Genehmigt", "承認済み", "Aprovado", "Утверждено", "Approvato", "已批准"],

    # Actions (3 keys)
    ["stories.action.edit", "Action Button", "Edit", "편집", "Editar", "تعديل", "संपादित करें", "Modifier", "Bearbeiten", "編集", "Editar", "Редактировать", "Modifica", "编辑"],
    ["stories.action.delete", "Action Button", "Delete", "삭제", "Eliminar", "حذف", "हटाएं", "Supprimer", "Löschen", "削除", "Excluir", "Удалить", "Elimina", "删除"],
    ["stories.action.view", "Action Button", "View Details", "상세보기", "Ver detalles", "عرض التفاصيل", "विवरण देखें", "Voir les détails", "Details anzeigen", "詳細を見る", "Ver detalhes", "Посмотреть детали", "Vedi dettagli", "查看详情"],
]

# Add common UI translations (6 keys)
common_translations = [
    ["common.loading", "Common UI", "Loading...", "로딩 중...", "Cargando...", "جاري التحميل...", "लोड हो रहा है...", "Chargement...", "Lädt...", "読み込み中...", "Carregando...", "Загрузка...", "Caricamento...", "加载中..."],
    ["common.error", "Common UI", "An error occurred", "오류가 발생했습니다", "Ocurrió un error", "حدث خطأ", "एक त्रुटि हुई", "Une erreur s'est produite", "Ein Fehler ist aufgetreten", "エラーが発生しました", "Ocorreu um erro", "Произошла ошибка", "Si è verificato un errore", "发生错误"],
    ["common.success", "Common UI", "Success", "성공", "Éxito", "نجاح", "सफलता", "Succès", "Erfolg", "成功", "Sucesso", "Успех", "Successo", "成功"],
    ["common.cancel", "Common UI", "Cancel", "취소", "Cancelar", "إلغاء", "रद्द करें", "Annuler", "Abbrechen", "キャンセル", "Cancelar", "Отмена", "Annulla", "取消"],
    ["common.save", "Common UI", "Save", "저장", "Guardar", "حفظ", "सहेजें", "Enregistrer", "Speichern", "保存", "Salvar", "Сохранить", "Salva", "保存"],
    ["common.confirm", "Common UI", "Confirm", "확인", "Confirmar", "تأكيد", "पुष्टि करें", "Confirmer", "Bestätigen", "確認", "Confirmar", "Подтвердить", "Conferma", "确认"],
]

# Add notification translations (15 keys)
notification_translations = [
    ["notification.statusChanged", "Notification", "Your story status changed to {status}", "스토리 상태가 {status}(으)로 변경되었습니다", "El estado de tu historia cambió a {status}", "تغيرت حالة قصتك إلى {status}", "आपकी कहानी की स्थिति {status} में बदल गई", "Le statut de votre histoire a changé en {status}", "Ihr Story-Status wurde auf {status} geändert", "ストーリーのステータスが{status}に変更されました", "O status da sua história mudou para {status}", "Статус вашей истории изменился на {status}", "Lo stato della tua storia è cambiato in {status}", "您的故事状态已更改为{status}"],
    ["notification.feedbackReceived", "Notification", "New feedback received for {title}", "{title}에 대한 새 피드백을 받았습니다", "Nuevos comentarios recibidos para {title}", "تم استلام ملاحظات جديدة لـ {title}", "{title} के लिए नई प्रतिक्रिया प्राप्त हुई", "Nouveaux retours reçus pour {title}", "Neues Feedback für {title} erhalten", "{title}の新しいフィードバックを受け取りました", "Novo feedback recebido para {title}", "Получен новый отзыв для {title}", "Nuovo feedback ricevuto per {title}", "收到{title}的新反馈"],
    ["notification.storyApproved", "Notification", "Congratulations! Your story has been approved", "축하합니다! 스토리가 승인되었습니다", "¡Felicidades! Tu historia ha sido aprobada", "تهانينا! تمت الموافقة على قصتك", "बधाई हो! आपकी कहानी स्वीकृत हो गई है", "Félicitations! Votre histoire a été approuvée", "Glückwunsch! Ihre Geschichte wurde genehmigt", "おめでとうございます！ストーリーが承認されました", "Parabéns! Sua história foi aprovada", "Поздравляем! Ваша история одобрена", "Congratulazioni! La tua storia è stata approvata", "恭喜！您的故事已获批准"],
    ["notification.revisionRequested", "Notification", "Revision requested for your story", "스토리에 대한 수정이 요청되었습니다", "Revisión solicitada para tu historia", "تم طلب مراجعة لقصتك", "आपकी कहानी के लिए संशोधन का अनुरोध किया गया", "Révision demandée pour votre histoire", "Überarbeitung für Ihre Geschichte angefordert", "ストーリーの修正がリクエストされました", "Revisão solicitada para sua história", "Запрошена доработка вашей истории", "Revisione richiesta per la tua storia", "已请求修改您的故事"],
    ["notification.storyPublished", "Notification", "Your story has been published!", "스토리가 출판되었습니다!", "¡Tu historia ha sido publicada!", "تم نشر قصتك!", "आपकी कहानी प्रकाशित हो गई है!", "Votre histoire a été publiée!", "Ihre Geschichte wurde veröffentlicht!", "ストーリーが公開されました！", "Sua história foi publicada!", "Ваша история опубликована!", "La tua storia è stata pubblicata!", "您的故事已发布！"],

    # Success/Error messages (10 keys)
    ["notification.saveSuccess", "Success Message", "Story saved successfully", "스토리가 성공적으로 저장되었습니다", "Historia guardada exitosamente", "تم حفظ القصة بنجاح", "कहानी सफलतापूर्वक सहेजी गई", "Histoire enregistrée avec succès", "Geschichte erfolgreich gespeichert", "ストーリーが正常に保存されました", "História salva com sucesso", "История успешно сохранена", "Storia salvata con successo", "故事保存成功"],
    ["notification.saveError", "Error Message", "Failed to save story. Please try again.", "스토리 저장에 실패했습니다. 다시 시도해 주세요.", "No se pudo guardar la historia. Por favor, inténtalo de nuevo.", "فشل حفظ القصة. يرجى المحاولة مرة أخرى.", "कहानी सहेजने में विफल। कृपया पुनः प्रयास करें.", "Échec de l'enregistrement de l'histoire. Veuillez réessayer.", "Speichern der Geschichte fehlgeschlagen. Bitte versuchen Sie es erneut.", "ストーリーの保存に失敗しました。もう一度お試しください。", "Falha ao salvar história. Por favor, tente novamente.", "Не удалось сохранить историю. Попробуйте снова.", "Impossibile salvare la storia. Riprova.", "保存故事失败。请重试。"],
    ["notification.submitSuccess", "Success Message", "Story submitted for review", "검토를 위해 스토리가 제출되었습니다", "Historia enviada para revisión", "تم إرسال القصة للمراجعة", "समीक्षा के लिए कहानी सबमिट की गई", "Histoire soumise pour révision", "Geschichte zur Überprüfung eingereicht", "レビューのためにストーリーが提出されました", "História enviada para revisão", "История отправлена на рассмотрение", "Storia inviata per la revisione", "故事已提交审核"],
    ["notification.submitError", "Error Message", "Failed to submit story. Please try again.", "스토리 제출에 실패했습니다. 다시 시도해 주세요.", "No se pudo enviar la historia. Por favor, inténtalo de nuevo.", "فشل إرسال القصة. يرجى المحاولة مرة أخرى.", "कहानी सबमिट करने में विफल। कृपया पुनः प्रयास करें.", "Échec de l'envoi de l'histoire. Veuillez réessayer.", "Einreichung der Geschichte fehlgeschlagen. Bitte versuchen Sie es erneut.", "ストーリーの提出に失敗しました。もう一度お試しください。", "Falha ao enviar história. Por favor, tente novamente.", "Не удалось отправить историю. Попробуйте снова.", "Impossibile inviare la storia. Riprova.", "提交故事失败。请重试。"],
    ["notification.deleteSuccess", "Success Message", "Story deleted successfully", "스토리가 성공적으로 삭제되었습니다", "Historia eliminada exitosamente", "تم حذف القصة بنجاح", "कहानी सफलतापूर्वक हटा दी गई", "Histoire supprimée avec succès", "Geschichte erfolgreich gelöscht", "ストーリーが正常に削除されました", "História excluída com sucesso", "История успешно удалена", "Storia eliminata con successo", "故事删除成功"],
    ["notification.deleteError", "Error Message", "Failed to delete story. Please try again.", "스토리 삭제에 실패했습니다. 다시 시도해 주세요.", "No se pudo eliminar la historia. Por favor, inténtalo de nuevo.", "فشل حذف القصة. يرجى المحاولة مرة أخرى.", "कहानी हटाने में विफल। कृपया पुनः प्रयास करें.", "Échec de la suppression de l'histoire. Veuillez réessayer.", "Löschen der Geschichte fehlgeschlagen. Bitte versuchen Sie es erneut.", "ストーリーの削除に失敗しました。もう一度お試しください。", "Falha ao excluir história. Por favor, tente novamente.", "Не удалось удалить историю. Попробуйте снова.", "Impossibile eliminare la storia. Riprova.", "删除故事失败。请重试。"],
    ["notification.withdrawSuccess", "Success Message", "Submission withdrawn successfully", "제출이 성공적으로 철회되었습니다", "Envío retirado exitosamente", "تم سحب التقديم بنجاح", "सबमिशन सफलतापूर्वक वापस ली गई", "Soumission retirée avec succès", "Einreichung erfolgreich zurückgezogen", "提出が正常に撤回されました", "Envio retirado com sucesso", "Заявка успешно отозвана", "Invio ritirato con successo", "提交已成功撤回"],
    ["notification.withdrawError", "Error Message", "Failed to withdraw submission. Please try again.", "제출 철회에 실패했습니다. 다시 시도해 주세요.", "No se pudo retirar el envío. Por favor, inténtalo de nuevo.", "فشل سحب التقديم. يرجى المحاولة مرة أخرى.", "सबमिशन वापस लेने में विफल। कृपया पुनः प्रयास करें.", "Échec du retrait de la soumission. Veuillez réessayer.", "Zurückziehen der Einreichung fehlgeschlagen. Bitte versuchen Sie es erneut.", "提出の撤回に失敗しました。もう一度お試しください。", "Falha ao retirar envio. Por favor, tente novamente.", "Не удалось отозвать заявку. Попробуйте снова.", "Impossibile ritirare l'invio. Riprova.", "撤回提交失败。请重试。"],
    ["notification.updateSuccess", "Success Message", "Story updated successfully", "스토리가 성공적으로 업데이트되었습니다", "Historia actualizada exitosamente", "تم تحديث القصة بنجاح", "कहानी सफलतापूर्वक अपडेट की गई", "Histoire mise à jour avec succès", "Geschichte erfolgreich aktualisiert", "ストーリーが正常に更新されました", "História atualizada com sucesso", "История успешно обновлена", "Storia aggiornata con successo", "故事更新成功"],
    ["notification.updateError", "Error Message", "Failed to update story. Please try again.", "스토리 업데이트에 실패했습니다. 다시 시도해 주세요.", "No se pudo actualizar la historia. Por favor, inténtalo de nuevo.", "فشل تحديث القصة. يرجى المحاولة مرة أخرى.", "कहानी अपडेट करने में विफल। कृपया पुनः प्रयास करें.", "Échec de la mise à jour de l'histoire. Veuillez réessayer.", "Aktualisierung der Geschichte fehlgeschlagen. Bitte versuchen Sie es erneut.", "ストーリーの更新に失敗しました。もう一度お試しください。", "Falha ao atualizar história. Por favor, tente novamente.", "Не удалось обновить историю. Попробуйте снова.", "Impossibile aggiornare la storia. Riprova.", "更新故事失败。请重试。"],
]

# Combine all translations
all_translations = (
    new_translations +
    about_translations +
    footer_translations +
    stories_translations +
    common_translations +
    notification_translations
)

# Read existing CSV
input_file = '/Users/jihunkong/1001project/1001-stories/locales/translations.csv'
output_file = '/Users/jihunkong/1001project/1001-stories/locales/translations.csv'

existing_rows = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    existing_rows = list(reader)

# Append new translations
with open(output_file, 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)

    # Write existing rows
    writer.writerows(existing_rows)

    # Write new rows
    writer.writerows(all_translations)

print(f"Successfully added {len(all_translations)} translation keys to {output_file}")
print(f"Total rows: {len(existing_rows) + len(all_translations)}")
